# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hologui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class MyQGraphicsView(QtWidgets.QGraphicsView):

    def __init__ (self, parent=None):
        super(MyQGraphicsView, self).__init__ (parent)

    def wheelEvent(self, event):
        # Zoom Factor
        zoomInFactor = 1.25
        zoomOutFactor = 1 / zoomInFactor

        # Set Anchors
        self.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)

        # Save the scene pos
        oldPos = self.mapToScene(event.pos())

        # Zoom
        if event.angleDelta().y() > 0:
            zoomFactor = zoomInFactor
        else:
            zoomFactor = zoomOutFactor
        self.scale(zoomFactor, zoomFactor)

        # Get the new position
        newPos = self.mapToScene(event.pos())

        # Move scene to old position
        delta = newPos - oldPos
        self.translate(delta.x(), delta.y())

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 634)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/prefix/Hologuy logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background: url(:/home/markus/Progs/iGEM_Darmstadt_Technik/owl.png)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GraphicsViewDarkField = QtWidgets.QGraphicsView(self.centralwidget)
        self.GraphicsViewDarkField.setGeometry(QtCore.QRect(11, 2, 256, 256))
        self.GraphicsViewDarkField.setObjectName("GraphicsViewDarkField")
        self.GraphicsViewBackground = QtWidgets.QGraphicsView(self.centralwidget)
        self.GraphicsViewBackground.setGeometry(QtCore.QRect(273, 2, 256, 256))
        self.GraphicsViewBackground.setObjectName("GraphicsViewBackground")
        self.GraphicsViewSample = QtWidgets.QGraphicsView(self.centralwidget)
        self.GraphicsViewSample.setGeometry(QtCore.QRect(535, 2, 256, 256))
        self.GraphicsViewSample.setObjectName("GraphicsViewSample")
        self.LabelDarkFieldImage = QtWidgets.QLabel(self.centralwidget)
        self.LabelDarkFieldImage.setGeometry(QtCore.QRect(11, 260, 256, 17))
        self.LabelDarkFieldImage.setObjectName("LabelDarkFieldImage")
        self.LabelBackgoundImage = QtWidgets.QLabel(self.centralwidget)
        self.LabelBackgoundImage.setGeometry(QtCore.QRect(273, 260, 100, 17))
        self.LabelBackgoundImage.setObjectName("LabelBackgoundImage")
        self.LabelRawHologramImage = QtWidgets.QLabel(self.centralwidget)
        self.LabelRawHologramImage.setGeometry(QtCore.QRect(535, 260, 100, 17))
        self.LabelRawHologramImage.setObjectName("LabelRawHologramImage")
        self.GraphicsViewHologram = MyQGraphicsView(self.centralwidget)
        self.GraphicsViewHologram.setGeometry(QtCore.QRect(535, 280, 256, 256))
        self.GraphicsViewHologram.setObjectName("GraphicsViewHologram")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(271, 290, 151, 161))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PushButtonBackground = QtWidgets.QPushButton(self.frame_3)
        self.PushButtonBackground.setObjectName("PushButtonBackground")
        self.verticalLayout.addWidget(self.PushButtonBackground)
        self.PushButtonSample = QtWidgets.QPushButton(self.frame_3)
        self.PushButtonSample.setObjectName("PushButtonSample")
        self.verticalLayout.addWidget(self.PushButtonSample)
        self.PushButtonDarkField = QtWidgets.QPushButton(self.frame_3)
        self.PushButtonDarkField.setObjectName("PushButtonDarkField")
        self.verticalLayout.addWidget(self.PushButtonDarkField)
        self.PushButtonHologram = QtWidgets.QPushButton(self.frame_3)
        self.PushButtonHologram.setEnabled(False)
        self.PushButtonHologram.setObjectName("PushButtonHologram")
        self.verticalLayout.addWidget(self.PushButtonHologram)
        self.HorizontalSliderHologram = QtWidgets.QSlider(self.centralwidget)
        self.HorizontalSliderHologram.setEnabled(False)
        self.HorizontalSliderHologram.setGeometry(QtCore.QRect(535, 540, 251, 17))
        self.HorizontalSliderHologram.setOrientation(QtCore.Qt.Horizontal)
        self.HorizontalSliderHologram.setObjectName("HorizontalSliderHologram")
        self.LabelHologramImage = QtWidgets.QLabel(self.centralwidget)
        self.LabelHologramImage.setGeometry(QtCore.QRect(540, 560, 137, 17))
        self.LabelHologramImage.setObjectName("LabelHologramImage")
        self.TabSources = QtWidgets.QTabWidget(self.centralwidget)
        self.TabSources.setGeometry(QtCore.QRect(10, 280, 221, 301))
        self.TabSources.setObjectName("TabSources")
        self.TabPoint = QtWidgets.QWidget()
        self.TabPoint.setObjectName("TabPoint")
        self.frame = QtWidgets.QFrame(self.TabPoint)
        self.frame.setGeometry(QtCore.QRect(0, 0, 211, 262))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.SpinBoxSpacing = QtWidgets.QDoubleSpinBox(self.frame)
        self.SpinBoxSpacing.setDecimals(4)
        self.SpinBoxSpacing.setMaximum(1000.0)
        self.SpinBoxSpacing.setSingleStep(0.001)
        self.SpinBoxSpacing.setProperty("value", 1.12)
        self.SpinBoxSpacing.setObjectName("SpinBoxSpacing")
        self.gridLayout.addWidget(self.SpinBoxSpacing, 0, 0, 1, 1)
        self.LabelSpacing = QtWidgets.QLabel(self.frame)
        self.LabelSpacing.setObjectName("LabelSpacing")
        self.gridLayout.addWidget(self.LabelSpacing, 0, 1, 1, 1)
        self.SpinBoxWavelength = QtWidgets.QDoubleSpinBox(self.frame)
        self.SpinBoxWavelength.setMaximum(2000.0)
        self.SpinBoxWavelength.setProperty("value", 450.0)
        self.SpinBoxWavelength.setObjectName("SpinBoxWavelength")
        self.gridLayout.addWidget(self.SpinBoxWavelength, 1, 0, 1, 1)
        self.LabelWavelength = QtWidgets.QLabel(self.frame)
        self.LabelWavelength.setObjectName("LabelWavelength")
        self.gridLayout.addWidget(self.LabelWavelength, 1, 1, 1, 1)
        self.SpinBoxMedium = QtWidgets.QDoubleSpinBox(self.frame)
        self.SpinBoxMedium.setEnabled(False)
        self.SpinBoxMedium.setMinimum(1.0)
        self.SpinBoxMedium.setMaximum(1.0)
        self.SpinBoxMedium.setObjectName("SpinBoxMedium")
        self.gridLayout.addWidget(self.SpinBoxMedium, 2, 0, 1, 1)
        self.LabelMedium = QtWidgets.QLabel(self.frame)
        self.LabelMedium.setObjectName("LabelMedium")
        self.gridLayout.addWidget(self.LabelMedium, 2, 1, 1, 1)
        self.SpinBoxMagnification = QtWidgets.QDoubleSpinBox(self.frame)
        self.SpinBoxMagnification.setMaximum(200.0)
        self.SpinBoxMagnification.setProperty("value", 2.0)
        self.SpinBoxMagnification.setObjectName("SpinBoxMagnification")
        self.gridLayout.addWidget(self.SpinBoxMagnification, 3, 0, 1, 1)
        self.LabelPolarization = QtWidgets.QLabel(self.frame)
        self.LabelPolarization.setObjectName("LabelPolarization")
        self.gridLayout.addWidget(self.LabelPolarization, 3, 1, 1, 1)
        self.SpinBoxDistance = QtWidgets.QDoubleSpinBox(self.frame)
        self.SpinBoxDistance.setDecimals(3)
        self.SpinBoxDistance.setMaximum(10000.0)
        self.SpinBoxDistance.setProperty("value", 9.0)
        self.SpinBoxDistance.setObjectName("SpinBoxDistance")
        self.gridLayout.addWidget(self.SpinBoxDistance, 4, 0, 1, 1)
        self.LabelDistance = QtWidgets.QLabel(self.frame)
        self.LabelDistance.setObjectName("LabelDistance")
        self.gridLayout.addWidget(self.LabelDistance, 4, 1, 1, 1)
        self.SpinBoxZMin = QtWidgets.QDoubleSpinBox(self.frame)
        self.SpinBoxZMin.setDecimals(3)
        self.SpinBoxZMin.setMaximum(1000000.0)
        self.SpinBoxZMin.setProperty("value", 4600.0)
        self.SpinBoxZMin.setObjectName("SpinBoxZMin")
        self.gridLayout.addWidget(self.SpinBoxZMin, 5, 0, 1, 1)
        self.LabelZMin = QtWidgets.QLabel(self.frame)
        self.LabelZMin.setObjectName("LabelZMin")
        self.gridLayout.addWidget(self.LabelZMin, 5, 1, 1, 1)
        self.SpinBoxZMax = QtWidgets.QDoubleSpinBox(self.frame)
        self.SpinBoxZMax.setDecimals(3)
        self.SpinBoxZMax.setMaximum(100000.0)
        self.SpinBoxZMax.setProperty("value", 4700.0)
        self.SpinBoxZMax.setObjectName("SpinBoxZMax")
        self.gridLayout.addWidget(self.SpinBoxZMax, 6, 0, 1, 1)
        self.LabelZMax = QtWidgets.QLabel(self.frame)
        self.LabelZMax.setObjectName("LabelZMax")
        self.gridLayout.addWidget(self.LabelZMax, 6, 1, 1, 1)
        self.SpinBoxZStep = QtWidgets.QSpinBox(self.frame)
        self.SpinBoxZStep.setMaximum(1000)
        self.SpinBoxZStep.setProperty("value", 10)
        self.SpinBoxZStep.setObjectName("SpinBoxZStep")
        self.gridLayout.addWidget(self.SpinBoxZStep, 7, 0, 1, 1)
        self.SpinBoxNPixOut = QtWidgets.QSpinBox(self.frame)
        self.SpinBoxNPixOut.setMaximum(10000)
        self.SpinBoxNPixOut.setProperty("value", 1944)
        self.SpinBoxNPixOut.setObjectName("SpinBoxNPixOut")
        self.gridLayout.addWidget(self.SpinBoxNPixOut, 8, 0, 1, 1)
        self.LabelZSteps = QtWidgets.QLabel(self.frame)
        self.LabelZSteps.setObjectName("LabelZSteps")
        self.gridLayout.addWidget(self.LabelZSteps, 7, 1, 1, 1)
        self.LabelZNPixOut = QtWidgets.QLabel(self.frame)
        self.LabelZNPixOut.setObjectName("LabelZNPixOut")
        self.gridLayout.addWidget(self.LabelZNPixOut, 8, 1, 1, 1)
        self.TabSources.addTab(self.TabPoint, "")
        self.TabColl = QtWidgets.QWidget()
        self.TabColl.setObjectName("TabColl")
        self.frame_2 = QtWidgets.QFrame(self.TabColl)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 211, 262))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SpinBoxSpacing_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.SpinBoxSpacing_2.setDecimals(4)
        self.SpinBoxSpacing_2.setMaximum(1000.0)
        self.SpinBoxSpacing_2.setSingleStep(0.001)
        self.SpinBoxSpacing_2.setProperty("value", 1.12)
        self.SpinBoxSpacing_2.setObjectName("SpinBoxSpacing_2")
        self.gridLayout_2.addWidget(self.SpinBoxSpacing_2, 0, 0, 1, 1)
        self.LabelSpacing_2 = QtWidgets.QLabel(self.frame_2)
        self.LabelSpacing_2.setObjectName("LabelSpacing_2")
        self.gridLayout_2.addWidget(self.LabelSpacing_2, 0, 1, 1, 1)
        self.SpinBoxWavelength_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.SpinBoxWavelength_2.setMaximum(2000.0)
        self.SpinBoxWavelength_2.setProperty("value", 460.0)
        self.SpinBoxWavelength_2.setObjectName("SpinBoxWavelength_2")
        self.gridLayout_2.addWidget(self.SpinBoxWavelength_2, 1, 0, 1, 1)
        self.LabelWavelength_2 = QtWidgets.QLabel(self.frame_2)
        self.LabelWavelength_2.setObjectName("LabelWavelength_2")
        self.gridLayout_2.addWidget(self.LabelWavelength_2, 1, 1, 1, 1)
        self.SpinBoxMedium_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.SpinBoxMedium_2.setEnabled(False)
        self.SpinBoxMedium_2.setMinimum(1.0)
        self.SpinBoxMedium_2.setMaximum(1.0)
        self.SpinBoxMedium_2.setObjectName("SpinBoxMedium_2")
        self.gridLayout_2.addWidget(self.SpinBoxMedium_2, 2, 0, 1, 1)
        self.LabelMedium_2 = QtWidgets.QLabel(self.frame_2)
        self.LabelMedium_2.setObjectName("LabelMedium_2")
        self.gridLayout_2.addWidget(self.LabelMedium_2, 2, 1, 1, 1)
        self.SpinBoxMagnification_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.SpinBoxMagnification_2.setMaximum(200.0)
        self.SpinBoxMagnification_2.setProperty("value", 5.0)
        self.SpinBoxMagnification_2.setObjectName("SpinBoxMagnification_2")
        self.gridLayout_2.addWidget(self.SpinBoxMagnification_2, 3, 0, 1, 1)
        self.LabelPolarization_2 = QtWidgets.QLabel(self.frame_2)
        self.LabelPolarization_2.setObjectName("LabelPolarization_2")
        self.gridLayout_2.addWidget(self.LabelPolarization_2, 3, 1, 1, 1)
        self.SpinBoxDistance_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.SpinBoxDistance_2.setDecimals(3)
        self.SpinBoxDistance_2.setMaximum(10000.0)
        self.SpinBoxDistance_2.setProperty("value", 15.0)
        self.SpinBoxDistance_2.setObjectName("SpinBoxDistance_2")
        self.gridLayout_2.addWidget(self.SpinBoxDistance_2, 4, 0, 1, 1)
        self.LabelDistance_2 = QtWidgets.QLabel(self.frame_2)
        self.LabelDistance_2.setObjectName("LabelDistance_2")
        self.gridLayout_2.addWidget(self.LabelDistance_2, 4, 1, 1, 1)
        self.SpinBoxZMin_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.SpinBoxZMin_2.setDecimals(3)
        self.SpinBoxZMin_2.setMaximum(1000000.0)
        self.SpinBoxZMin_2.setProperty("value", 7000.0)
        self.SpinBoxZMin_2.setObjectName("SpinBoxZMin_2")
        self.gridLayout_2.addWidget(self.SpinBoxZMin_2, 5, 0, 1, 1)
        self.LabelZMin_2 = QtWidgets.QLabel(self.frame_2)
        self.LabelZMin_2.setObjectName("LabelZMin_2")
        self.gridLayout_2.addWidget(self.LabelZMin_2, 5, 1, 1, 1)
        self.SpinBoxZMax_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.SpinBoxZMax_2.setDecimals(3)
        self.SpinBoxZMax_2.setMaximum(100000.0)
        self.SpinBoxZMax_2.setProperty("value", 11000.0)
        self.SpinBoxZMax_2.setObjectName("SpinBoxZMax_2")
        self.gridLayout_2.addWidget(self.SpinBoxZMax_2, 6, 0, 1, 1)
        self.LabelZMax_2 = QtWidgets.QLabel(self.frame_2)
        self.LabelZMax_2.setObjectName("LabelZMax_2")
        self.gridLayout_2.addWidget(self.LabelZMax_2, 6, 1, 1, 1)
        self.SpinBoxZStep_2 = QtWidgets.QSpinBox(self.frame_2)
        self.SpinBoxZStep_2.setMaximum(1000)
        self.SpinBoxZStep_2.setProperty("value", 10)
        self.SpinBoxZStep_2.setObjectName("SpinBoxZStep_2")
        self.gridLayout_2.addWidget(self.SpinBoxZStep_2, 7, 0, 1, 1)
        self.SpinBoxNPixOut_2 = QtWidgets.QSpinBox(self.frame_2)
        self.SpinBoxNPixOut_2.setMaximum(10000)
        self.SpinBoxNPixOut_2.setProperty("value", 1500)
        self.SpinBoxNPixOut_2.setObjectName("SpinBoxNPixOut_2")
        self.gridLayout_2.addWidget(self.SpinBoxNPixOut_2, 8, 0, 1, 1)
        self.LabelZSteps_2 = QtWidgets.QLabel(self.frame_2)
        self.LabelZSteps_2.setObjectName("LabelZSteps_2")
        self.gridLayout_2.addWidget(self.LabelZSteps_2, 7, 1, 1, 1)
        self.LabelZNPixOut_2 = QtWidgets.QLabel(self.frame_2)
        self.LabelZNPixOut_2.setObjectName("LabelZNPixOut_2")
        self.gridLayout_2.addWidget(self.LabelZNPixOut_2, 8, 1, 1, 1)
        self.TabSources.addTab(self.TabColl, "")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(270, 460, 151, 111))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(14, 10, 121, 29))
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar.setGeometry(QtCore.QRect(20, 60, 111, 23))
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.HoloGramData = QtWidgets.QLabel(self.centralwidget)
        self.HoloGramData.setGeometry(QtCore.QRect(730, 560, 54, 17))
        self.HoloGramData.setText("")
        self.HoloGramData.setObjectName("HoloGramData")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Config = QtWidgets.QAction(MainWindow)
        self.actionLoad_Config.setObjectName("actionLoad_Config")
        self.actionSave_Config = QtWidgets.QAction(MainWindow)
        self.actionSave_Config.setObjectName("actionSave_Config")
        self.actionSave_Hologram_as = QtWidgets.QAction(MainWindow)
        self.actionSave_Hologram_as.setObjectName("actionSave_Hologram_as")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_averaged_background = QtWidgets.QAction(MainWindow)
        self.actionSave_averaged_background.setObjectName("actionSave_averaged_background")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoad_Config)
        self.menuFile.addAction(self.actionSave_Config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Hologram_as)
        self.menuFile.addAction(self.actionSave_averaged_background)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.TabSources.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HoloGui"))
        self.LabelDarkFieldImage.setText(_translate("MainWindow", "Reference Reconstruction"))
        self.LabelBackgoundImage.setText(_translate("MainWindow", "Background"))
        self.LabelRawHologramImage.setText(_translate("MainWindow", "Hologram"))
        self.PushButtonBackground.setText(_translate("MainWindow", "Open Background"))
        self.PushButtonSample.setText(_translate("MainWindow", "Load Sample"))
        self.PushButtonDarkField.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>This is a button</p></body></html>"))
        self.PushButtonDarkField.setText(_translate("MainWindow", "Set Reference Pic"))
        self.PushButtonHologram.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>This is a button</p></body></html>"))
        self.PushButtonHologram.setText(_translate("MainWindow", "Reconstruct"))
        self.LabelHologramImage.setText(_translate("MainWindow", "Reconstructed Images"))
        self.LabelSpacing.setText(_translate("MainWindow", "Spacing [µm]"))
        self.LabelWavelength.setText(_translate("MainWindow", "Wavelength [nm]"))
        self.LabelMedium.setText(_translate("MainWindow", "Medium"))
        self.LabelPolarization.setText(_translate("MainWindow", "Magnification"))
        self.LabelDistance.setText(_translate("MainWindow", "Distance [mm]"))
        self.LabelZMin.setText(_translate("MainWindow", "Z min [µm]"))
        self.LabelZMax.setText(_translate("MainWindow", "Z max [µm]"))
        self.LabelZSteps.setText(_translate("MainWindow", "Z steps"))
        self.LabelZNPixOut.setText(_translate("MainWindow", "Outpixel [#]"))
        self.TabSources.setTabText(self.TabSources.indexOf(self.TabPoint), _translate("MainWindow", "Point Source"))
        self.LabelSpacing_2.setText(_translate("MainWindow", "Spacing [µm]"))
        self.LabelWavelength_2.setText(_translate("MainWindow", "Wavelength [nm]"))
        self.LabelMedium_2.setText(_translate("MainWindow", "Medium"))
        self.LabelPolarization_2.setText(_translate("MainWindow", "Magnification"))
        self.LabelDistance_2.setText(_translate("MainWindow", "Distance [mm]"))
        self.LabelZMin_2.setText(_translate("MainWindow", "Z min [µm]"))
        self.LabelZMax_2.setText(_translate("MainWindow", "Z max [µm]"))
        self.LabelZSteps_2.setText(_translate("MainWindow", "Z steps"))
        self.LabelZNPixOut_2.setText(_translate("MainWindow", "Outpixel [#]"))
        self.TabSources.setTabText(self.TabSources.indexOf(self.TabColl), _translate("MainWindow", "Collimated Source"))
        self.pushButton.setText(_translate("MainWindow", "Show 3D Object"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.actionLoad_Config.setText(_translate("MainWindow", "&Load Config"))
        self.actionSave_Config.setText(_translate("MainWindow", "&Save Config"))
        self.actionSave_Hologram_as.setText(_translate("MainWindow", "Save &Hologram as..."))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionSave_averaged_background.setText(_translate("MainWindow", "Save Averaged &Background"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))

import hologui_rc
